# Generated by Django 6.0.7 on 2026-08-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_bio_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Livre rendu'),)},
        ),
    ]
